17media/announcement

prod/announcement.yaml

From 2020-05-07 05:20:00 to 2020-05-07 05:50:00
https://17media.slack.com/archives/C0PAD7W5R/p1588657495063800

Set prod maintenance 2020-05-07 05:20:00

---

dev/17app/announcement.yaml
dev/event-server/announcement.yaml
prod/17app/announcement.yaml
prod/event-server/announcement.yaml
sta/17app/announcement.yaml
sta/event-server/announcement.yaml

Ref: https://github.com/17media/api/pull/9605

Add configs for 17app and event-server

---

dev/17app/announcement.yaml
prod/17app/announcement.yaml
sta/17app/announcement.yaml

Ref: https://17media.slack.com/archives/G905XF0NB/p1593656652214300?thread_ts=1592449872.126300&cid=G905XF0NB

Update announcement description

---

dev/17app/announcement.yaml
dev/event-server/announcement.yaml

Reverts 17media/announcement#36

Revert "test in pre-prod"

---

sta/17app/announcement.yaml

For QA Ray Miao test purpose in pre-prod

Update announcement.yaml in stag

---

sta/17app/announcement.yaml

per request from Ray Miao (HQ QA)

[PreProd] Update announcement.yaml for testing in 1900-1910

---

sta/17app/announcement.yaml

https://17media.slack.com/archives/C466YU363/p1639040181436800

Pre-prod 2021-12-09 1830 redisv2 persist migrate

---

sta/17app/announcement.yaml

https://17media.slack.com/archives/C466YU363/p1641890875123800

redisv2 persist rollback

---

sta/17app/announcement.yaml

https://17media.slack.com/archives/C466YU363/p1641890875123800

redisv2 persist migrate

---

sta/17app/announcement.yaml
sta/event-server/announcement.yaml

ref: https://17media.slack.com/archives/C0PAD7W5R/p1641975177045800

test announcement in stag

---

dev/17app/announcement.yaml
prod/17app/announcement.yaml
sta/17app/announcement.yaml
uat/17app/announcement.yaml

- New field "image" in /announcement for system maintenance baby image.
- New field value is configurable.
- Config is in announcement.yaml.
**new field "image " in api**
```json
{
"startTime": 1643127133,
"startTime": 1643127134,
"title": "System Maintenance",
"description": "Dear users,\n
Our servers will be down for routine maintenance from 2022/01/18 20:10 UTC to 2022/01/18 20:20. We apologize for the inconvenience!",
"pic": "17baobao.jpg",
"image": "0f98f7d8-e753-4e4e-b222-1db9a1a1b3cd.png" // new field
}
```
**new field "image" in announcement.yaml**
Change new field "image" value if you want to change system maintenance image.
```yaml
needMaintenance: true
sendPubnub: true
startAt: 2022-01-19 04:10:00 (GMT+0800)
endAt: 2022-01-19 04:20:00 (GMT+0800)
image: …
```

[APP-33466] Create a new icon field for system maintenance baby image.

---

dev/17app/announcement.yaml
prod/17app/announcement.yaml
sta/17app/announcement.yaml
uat/17app/announcement.yaml

**change field "image" value in announcement.yaml**
```yaml
"image": "1032766c-4027-4d6e-8f48-6a46d02a50a0.png" // change  image field
```
All language classification are same image.
https://17media.atlassian.net/browse/APP-33466

[APP-33466] change announcement image filed image value

---

prod/event-server/announcement.yaml

https://17media.slack.com/archives/C0PAD7W5R/p1649657170850599

announcement for redis migration at 4/19

---

prod/17app/announcement.yaml

https://17media.slack.com/archives/C0PAD7W5R/p1675840155040509

[Infra][Prod] Upgrade MySQL announcement

---

prod/17app/announcement.yaml

[MySQL Version Update Announcement]
https://17media.slack.com/archives/C0PAD7W5R/p1692084969062769

[Infra][Prod] Update announcement

---

sta/17app/announcement.yaml

https://17media.slack.com/archives/C03V8JH0Q02/p1731986828640139
https://17media.slack.com/archives/G8L6JKY02/p1731915029601779

[SRE-8157] test the maintenance mode

---

prod/17app/announcement.yaml

https://17media.slack.com/archives/C0PAD7W5R/p1732007273411259

[SRE-8177] ably fallback host

---

prod/17app/announcement.yaml

https://17media.atlassian.net/browse/SRE-8181

revert commit

---

dev/17app/announcement.yaml
sta/17app/announcement.yaml
uat/17app/announcement.yaml

update announcement config
https://17media.atlassian.net/browse/APP-102169

[APP-102169] update announcement config

---

dev/event-server/announcement.yaml
prod/17app/announcement.yaml
prod/event-server/announcement.yaml
sta/17app/announcement.yaml
sta/event-server/announcement.yaml
uat/17app/announcement.yaml
uat/event-server/announcement.yaml

https://17media.atlassian.net/browse/APP-107116
set PROD using ably only

[APP-107116] update PROD config

---

dev/wave/announcement.yaml
prod/wave/announcement.yaml
sta/wave/announcement.yaml
uat/wave/announcement.yaml

[WAVE-5717] Add `providersToUse` configuration for messengerv2
[WAVE-5717]: https://17media.atlassian.net/browse/WAVE-5717

[WAVE-5717] Add `providersToUse` configuration for messengerv2

---

sta/17app/announcement.yaml

For the MySQL upgrade, test the maintenance mode in the stag environment.
Align the prod [yaml](https://github.com/17media/announcement/blob/master/prod/17app/announcement.yaml) file
Slack: https://17media.slack.com/archives/C03V8JH0Q02/p1742442731749709
Jira: https://17media.atlassian.net/browse/SRE-8909

[SRE] Update announcement.yaml

---

prod/17app/announcement.yaml

MySQL 5.7 upgrade to 8.0 maintenance mode
Time: 5/12(一) 05:00am ~ 06:30am
Jira: https://17media.atlassian.net/browse/SRE-5471
Slack: https://17media.slack.com/archives/C0PAD7W5R/p1741857690840569

[SRE-5471] Upgrade MySQL announcement
